/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DeskRouteRouteImport } from './routes/desk/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppJourneyRouteImport } from './routes/_app/journey'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppTripRouteImport } from './routes/_app/trip'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskCalendarRouteImport } from './routes/desk/calendar'
import { Route as DeskHomesRouteImport } from './routes/desk/homes'
import { Route as DeskLeadsRouteImport } from './routes/desk/leads'
import { Route as DeskLiveRouteImport } from './routes/desk/live'
import { Route as DeskOffersRouteImport } from './routes/desk/offers'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as AppHomesIdRouteImport } from './routes/_app/homes.$id'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages.index'
import { Route as AppMessagesIdRouteImport } from './routes/_app/messages.$id'
import { Route as AppOffersIndexRouteImport } from './routes/_app/offers.index'
import { Route as AppOffersIdRouteImport } from './routes/_app/offers.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DeskHomesIndexRouteImport } from './routes/desk/homes.index'
import { Route as DeskHomesIdRouteImport } from './routes/desk/homes.$id'
import { Route as DeskOffersIndexRouteImport } from './routes/desk/offers.index'
import { Route as DeskOffersIdRouteImport } from './routes/desk/offers.$id'
import { Route as AppHomesIdIndexRouteImport } from './routes/_app/homes.$id.index'
import { Route as AppHomesIdOfferRouteImport } from './routes/_app/homes.$id.offer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRouteRoute = DeskRouteRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTripRoute = AppTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => AppRouteRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskCalendarRoute = DeskCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskHomesRoute = DeskHomesRouteImport.update({
  id: '/homes',
  path: '/homes',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskLeadsRoute = DeskLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskLiveRoute = DeskLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskOffersRoute = DeskOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DeskRouteRoute,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomesIdRoute = AppHomesIdRouteImport.update({
  id: '/homes/$id',
  path: '/homes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppOffersIndexRoute = AppOffersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOffersRoute,
} as any)
const AppOffersIdRoute = AppOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOffersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskHomesIndexRoute = DeskHomesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskHomesRoute,
} as any)
const DeskHomesIdRoute = DeskHomesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskHomesRoute,
} as any)
const DeskOffersIndexRoute = DeskOffersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskOffersRoute,
} as any)
const DeskOffersIdRoute = DeskOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskOffersRoute,
} as any)
const AppHomesIdIndexRoute = AppHomesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomesIdRoute,
} as any)
const AppHomesIdOfferRoute = AppHomesIdOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => AppHomesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/compare': typeof AppCompareRoute
  '/home': typeof AppHomeRoute
  '/journey': typeof AppJourneyRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/offers': typeof AppOffersRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/services': typeof AppServicesRoute
  '/trip': typeof AppTripRoute
  '/desk/calendar': typeof DeskCalendarRoute
  '/desk/homes': typeof DeskHomesRouteWithChildren
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/live': typeof DeskLiveRoute
  '/desk/offers': typeof DeskOffersRouteWithChildren
  '/live/$id': typeof LiveIdRoute
  '/desk/': typeof DeskIndexRoute
  '/homes/$id': typeof AppHomesIdRouteWithChildren
  '/messages/$id': typeof AppMessagesIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/desk/homes/$id': typeof DeskHomesIdRoute
  '/desk/offers/$id': typeof DeskOffersIdRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/offers/': typeof AppOffersIndexRoute
  '/desk/homes/': typeof DeskHomesIndexRoute
  '/desk/offers/': typeof DeskOffersIndexRoute
  '/homes/$id/offer': typeof AppHomesIdOfferRoute
  '/homes/$id/': typeof AppHomesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/compare': typeof AppCompareRoute
  '/home': typeof AppHomeRoute
  '/journey': typeof AppJourneyRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/services': typeof AppServicesRoute
  '/trip': typeof AppTripRoute
  '/desk/calendar': typeof DeskCalendarRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/live': typeof DeskLiveRoute
  '/live/$id': typeof LiveIdRoute
  '/desk': typeof DeskIndexRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/offers/$id': typeof AppOffersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/desk/homes/$id': typeof DeskHomesIdRoute
  '/desk/offers/$id': typeof DeskOffersIdRoute
  '/messages': typeof AppMessagesIndexRoute
  '/offers': typeof AppOffersIndexRoute
  '/desk/homes': typeof DeskHomesIndexRoute
  '/desk/offers': typeof DeskOffersIndexRoute
  '/homes/$id/offer': typeof AppHomesIdOfferRoute
  '/homes/$id': typeof AppHomesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/desk': typeof DeskRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/journey': typeof AppJourneyRoute
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/offers': typeof AppOffersRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/trip': typeof AppTripRoute
  '/desk/calendar': typeof DeskCalendarRoute
  '/desk/homes': typeof DeskHomesRouteWithChildren
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/live': typeof DeskLiveRoute
  '/desk/offers': typeof DeskOffersRouteWithChildren
  '/live/$id': typeof LiveIdRoute
  '/desk/': typeof DeskIndexRoute
  '/_app/homes/$id': typeof AppHomesIdRouteWithChildren
  '/_app/messages/$id': typeof AppMessagesIdRoute
  '/_app/offers/$id': typeof AppOffersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/desk/homes/$id': typeof DeskHomesIdRoute
  '/desk/offers/$id': typeof DeskOffersIdRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/_app/offers/': typeof AppOffersIndexRoute
  '/desk/homes/': typeof DeskHomesIndexRoute
  '/desk/offers/': typeof DeskOffersIndexRoute
  '/_app/homes/$id/offer': typeof AppHomesIdOfferRoute
  '/_app/homes/$id/': typeof AppHomesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/login'
    | '/onboarding'
    | '/compare'
    | '/home'
    | '/journey'
    | '/messages'
    | '/offers'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/trip'
    | '/desk/calendar'
    | '/desk/homes'
    | '/desk/leads'
    | '/desk/live'
    | '/desk/offers'
    | '/live/$id'
    | '/desk/'
    | '/homes/$id'
    | '/messages/$id'
    | '/offers/$id'
    | '/api/auth/$'
    | '/desk/homes/$id'
    | '/desk/offers/$id'
    | '/messages/'
    | '/offers/'
    | '/desk/homes/'
    | '/desk/offers/'
    | '/homes/$id/offer'
    | '/homes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/compare'
    | '/home'
    | '/journey'
    | '/profile'
    | '/saved'
    | '/search'
    | '/services'
    | '/trip'
    | '/desk/calendar'
    | '/desk/leads'
    | '/desk/live'
    | '/live/$id'
    | '/desk'
    | '/messages/$id'
    | '/offers/$id'
    | '/api/auth/$'
    | '/desk/homes/$id'
    | '/desk/offers/$id'
    | '/messages'
    | '/offers'
    | '/desk/homes'
    | '/desk/offers'
    | '/homes/$id/offer'
    | '/homes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/desk'
    | '/login'
    | '/onboarding'
    | '/_app/compare'
    | '/_app/home'
    | '/_app/journey'
    | '/_app/messages'
    | '/_app/offers'
    | '/_app/profile'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/services'
    | '/_app/trip'
    | '/desk/calendar'
    | '/desk/homes'
    | '/desk/leads'
    | '/desk/live'
    | '/desk/offers'
    | '/live/$id'
    | '/desk/'
    | '/_app/homes/$id'
    | '/_app/messages/$id'
    | '/_app/offers/$id'
    | '/api/auth/$'
    | '/desk/homes/$id'
    | '/desk/offers/$id'
    | '/_app/messages/'
    | '/_app/offers/'
    | '/desk/homes/'
    | '/desk/offers/'
    | '/_app/homes/$id/offer'
    | '/_app/homes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DeskRouteRoute: typeof DeskRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  LiveIdRoute: typeof LiveIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/journey': {
      id: '/_app/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/trip': {
      id: '/_app/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof AppTripRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/calendar': {
      id: '/desk/calendar'
      path: '/calendar'
      fullPath: '/desk/calendar'
      preLoaderRoute: typeof DeskCalendarRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/homes': {
      id: '/desk/homes'
      path: '/homes'
      fullPath: '/desk/homes'
      preLoaderRoute: typeof DeskHomesRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/leads': {
      id: '/desk/leads'
      path: '/leads'
      fullPath: '/desk/leads'
      preLoaderRoute: typeof DeskLeadsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/live': {
      id: '/desk/live'
      path: '/live'
      fullPath: '/desk/live'
      preLoaderRoute: typeof DeskLiveRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/offers': {
      id: '/desk/offers'
      path: '/offers'
      fullPath: '/desk/offers'
      preLoaderRoute: typeof DeskOffersRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/homes/$id': {
      id: '/_app/homes/$id'
      path: '/homes/$id'
      fullPath: '/homes/$id'
      preLoaderRoute: typeof AppHomesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/messages/$id': {
      id: '/_app/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/offers/': {
      id: '/_app/offers/'
      path: '/'
      fullPath: '/offers/'
      preLoaderRoute: typeof AppOffersIndexRouteImport
      parentRoute: typeof AppOffersRoute
    }
    '/_app/offers/$id': {
      id: '/_app/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AppOffersIdRouteImport
      parentRoute: typeof AppOffersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/homes/': {
      id: '/desk/homes/'
      path: '/'
      fullPath: '/desk/homes/'
      preLoaderRoute: typeof DeskHomesIndexRouteImport
      parentRoute: typeof DeskHomesRoute
    }
    '/desk/homes/$id': {
      id: '/desk/homes/$id'
      path: '/$id'
      fullPath: '/desk/homes/$id'
      preLoaderRoute: typeof DeskHomesIdRouteImport
      parentRoute: typeof DeskHomesRoute
    }
    '/desk/offers/': {
      id: '/desk/offers/'
      path: '/'
      fullPath: '/desk/offers/'
      preLoaderRoute: typeof DeskOffersIndexRouteImport
      parentRoute: typeof DeskOffersRoute
    }
    '/desk/offers/$id': {
      id: '/desk/offers/$id'
      path: '/$id'
      fullPath: '/desk/offers/$id'
      preLoaderRoute: typeof DeskOffersIdRouteImport
      parentRoute: typeof DeskOffersRoute
    }
    '/_app/homes/$id/': {
      id: '/_app/homes/$id/'
      path: '/'
      fullPath: '/homes/$id/'
      preLoaderRoute: typeof AppHomesIdIndexRouteImport
      parentRoute: typeof AppHomesIdRoute
    }
    '/_app/homes/$id/offer': {
      id: '/_app/homes/$id/offer'
      path: '/offer'
      fullPath: '/homes/$id/offer'
      preLoaderRoute: typeof AppHomesIdOfferRouteImport
      parentRoute: typeof AppHomesIdRoute
    }
  }
}

interface AppMessagesRouteChildren {
  AppMessagesIdRoute: typeof AppMessagesIdRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesIdRoute: AppMessagesIdRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppOffersRouteChildren {
  AppOffersIdRoute: typeof AppOffersIdRoute
  AppOffersIndexRoute: typeof AppOffersIndexRoute
}

const AppOffersRouteChildren: AppOffersRouteChildren = {
  AppOffersIdRoute: AppOffersIdRoute,
  AppOffersIndexRoute: AppOffersIndexRoute,
}

const AppOffersRouteWithChildren = AppOffersRoute._addFileChildren(
  AppOffersRouteChildren,
)

interface AppHomesIdRouteChildren {
  AppHomesIdOfferRoute: typeof AppHomesIdOfferRoute
  AppHomesIdIndexRoute: typeof AppHomesIdIndexRoute
}

const AppHomesIdRouteChildren: AppHomesIdRouteChildren = {
  AppHomesIdOfferRoute: AppHomesIdOfferRoute,
  AppHomesIdIndexRoute: AppHomesIdIndexRoute,
}

const AppHomesIdRouteWithChildren = AppHomesIdRoute._addFileChildren(
  AppHomesIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppCompareRoute: typeof AppCompareRoute
  AppHomeRoute: typeof AppHomeRoute
  AppJourneyRoute: typeof AppJourneyRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppOffersRoute: typeof AppOffersRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppServicesRoute: typeof AppServicesRoute
  AppTripRoute: typeof AppTripRoute
  AppHomesIdRoute: typeof AppHomesIdRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCompareRoute: AppCompareRoute,
  AppHomeRoute: AppHomeRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppOffersRoute: AppOffersRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppServicesRoute: AppServicesRoute,
  AppTripRoute: AppTripRoute,
  AppHomesIdRoute: AppHomesIdRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DeskHomesRouteChildren {
  DeskHomesIdRoute: typeof DeskHomesIdRoute
  DeskHomesIndexRoute: typeof DeskHomesIndexRoute
}

const DeskHomesRouteChildren: DeskHomesRouteChildren = {
  DeskHomesIdRoute: DeskHomesIdRoute,
  DeskHomesIndexRoute: DeskHomesIndexRoute,
}

const DeskHomesRouteWithChildren = DeskHomesRoute._addFileChildren(
  DeskHomesRouteChildren,
)

interface DeskOffersRouteChildren {
  DeskOffersIdRoute: typeof DeskOffersIdRoute
  DeskOffersIndexRoute: typeof DeskOffersIndexRoute
}

const DeskOffersRouteChildren: DeskOffersRouteChildren = {
  DeskOffersIdRoute: DeskOffersIdRoute,
  DeskOffersIndexRoute: DeskOffersIndexRoute,
}

const DeskOffersRouteWithChildren = DeskOffersRoute._addFileChildren(
  DeskOffersRouteChildren,
)

interface DeskRouteRouteChildren {
  DeskCalendarRoute: typeof DeskCalendarRoute
  DeskHomesRoute: typeof DeskHomesRouteWithChildren
  DeskLeadsRoute: typeof DeskLeadsRoute
  DeskLiveRoute: typeof DeskLiveRoute
  DeskOffersRoute: typeof DeskOffersRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteRouteChildren: DeskRouteRouteChildren = {
  DeskCalendarRoute: DeskCalendarRoute,
  DeskHomesRoute: DeskHomesRouteWithChildren,
  DeskLeadsRoute: DeskLeadsRoute,
  DeskLiveRoute: DeskLiveRoute,
  DeskOffersRoute: DeskOffersRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteRouteWithChildren = DeskRouteRoute._addFileChildren(
  DeskRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DeskRouteRoute: DeskRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  LiveIdRoute: LiveIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
